import spanakopita from "../assets/images/foods/spanakopita.jpg"

export const greekDishes = [
  {
    name: "Σπανακόπιτα",
    description: "Φύλλο κρούστας γεμιστό με σπανάκι και φέτα.",
    image: spanakopita,
    price: 3.2,
    category: "Πίτα",
  },
  {
    name: "Τυρόπιτα",
    description: "Φύλλο κρούστας γεμιστό με μείγμα τυριών.",
    image: "images/tyropita.jpg",
    price: 3.0,
    category: "Πίτα",
  },
  {
    name: "Χωριάτικη Σαλάτα",
    description:
      "Ντομάτα, αγγούρι, κρεμμύδι, πιπεριά, ελιές και φέτα με ελαιόλαδο.",
    image: "images/xoriatiki.jpg",
    price: 6.0,
    category: "Σαλάτα",
  },
  {
    name: "Τζατζίκι",
    description: "Κρεμώδης σάλτσα από γιαούρτι, αγγούρι, σκόρδο και ελαιόλαδο.",
    image: "images/tzatziki.jpg",
    price: 3.0,
    category: "Ορεκτικό",
  },
  {
    name: "Ντολμαδάκια Γιαλαντζί",
    description:
      "Αμπελόφυλλα γεμιστά με ρύζι και μυρωδικά, σερβιρισμένα με λεμόνι.",
    image: "images/dolmadakia.jpg",
    price: 6.5,
    category: "Ορεκτικό",
  },
  {
    name: "Μελιτζανοσαλάτα",
    description: "Πουρές από ψητή μελιτζάνα με σκόρδο, ελαιόλαδο και λεμόνι.",
    image: "images/melitzanosalata.jpg",
    price: 4.0,
    category: "Ορεκτικό",
  },
  {
    name: "Κεφτεδάκια",
    description: "Τηγανητοί μπιφτεκάκια με κιμά, ψωμί και μυρωδικά.",
    image: "images/keftedes.jpg",
    price: 6.8,
    category: "Ορεκτικό",
  },
  {
    name: "Φάβα Σαντορίνης",
    description:
      "Πουρές από κίτρινα αρακά, σερβιρισμένος με κρεμμύδι και ελαιόλαδο.",
    image: "images/fava.jpg",
    price: 5.5,
    category: "Ορεκτικό",
  },
  {
    name: "Φασολάδα",
    description: "Παραδοσιακή σούπα φασολιών με λαχανικά και ελαιόλαδο.",
    image: "images/fasolada.jpg",
    price: 5.5,
    category: "Σούπα",
  },
  {
    name: "Κοτόσουπα Αυγολέμονο",
    description: "Παραδοσιακή σούπα κοτόπουλου με ρύζι και αυγολέμονο.",
    image: "images/avgolemono.jpg",
    price: 6.0,
    category: "Σούπα",
  },
  {
    name: "Χταποδάκι Σχάρας",
    description: "Ψητό χταπόδι στη σχάρα με λαδολέμονο.",
    image: "images/xtapodi.jpg",
    price: 12.0,
    category: "Θαλασσινά",
  },
  {
    name: "Καλαμαράκια Τηγανιτά",
    description:
      "Καλαμάρια κομμένα σε ροδέλες, τηγανισμένα σε τραγανό κουρκούτι.",
    image: "images/kalamarakia.jpg",
    price: 9.0,
    category: "Θαλασσινά",
  },
  {
    name: "Μπακαλιάρος Σκορδαλιά",
    description: "Τηγανητός μπακαλιάρος με σκορδαλιά πατάτας.",
    image: "images/bakaliaros-skordalia.jpg",
    price: 8.5,
    category: "Θαλασσινά",
  },
  {
    name: "Γαρίδες Σαγανάκι",
    description: "Γαρίδες σοταρισμένες σε σάλτσα ντομάτας με φέτα.",
    image: "images/garides-saganaki.jpg",
    price: 11.0,
    category: "Θαλασσινά",
  },
  {
    name: "Μουσακάς",
    description:
      "Στρώσεις πατάτας, μελιτζάνας και κιμά με μπεσαμέλ, ψημένος στο φούρνο.",
    image: "images/moussakas.jpg",
    price: 9.5,
    category: "Κυρίως Πιάτο",
  },
  {
    name: "Παστίτσιο",
    description: "Μακαρόνια με κιμά και μπεσαμέλ, ψημένα στο φούρνο.",
    image: "images/pastitsio.jpg",
    price: 8.9,
    category: "Κυρίως Πιάτο",
  },
  {
    name: "Σουβλάκι Χοιρινό",
    description: "Ψητό χοιρινό κρέας σε καλαμάκι, σερβιρισμένο με πίτα.",
    image: "images/souvlaki-xoirino.jpg",
    price: 3.5,
    category: "Κυρίως Πιάτο",
  },
  {
    name: "Γύρος Κοτόπουλο",
    description:
      "Ψητό κοτόπουλο σε πίτα με πατάτες, ντομάτα, κρεμμύδι και τζατζίκι.",
    image: "images/gyros-kotopoulo.jpg",
    price: 3.8,
    category: "Κυρίως Πιάτο",
  },
  {
    name: "Γεμιστά",
    description:
      "Ντομάτες και πιπεριές γεμιστές με ρύζι και μυρωδικά, ψημένες στο φούρνο.",
    image: "images/gemista.jpg",
    price: 7.5,
    category: "Κυρίως Πιάτο",
  },
  {
    name: "Μπριάμ",
    description: "Ψητά ανάμεικτα λαχανικά με ελαιόλαδο και μυρωδικά.",
    image: "images/briam.jpg",
    price: 6.0,
    category: "Κυρίως Πιάτο",
  },
  {
    name: "Κοτόπουλο Λεμονάτο",
    description: "Ψητό κοτόπουλο με πατάτες, λεμόνι, ρίγανη και ελαιόλαδο.",
    image: "images/kotopoulo-lemonato.jpg",
    price: 8.5,
    category: "Κυρίως Πιάτο",
  },
  {
    name: "Λαχανοντολμάδες",
    description: "Λάχανο γεμιστό με κιμά και ρύζι, σε σάλτσα αυγολέμονο.",
    image: "images/lahanontolmades.jpg",
    price: 7.0,
    category: "Κυρίως Πιάτο",
  },
  {
    name: "Στιφάδο",
    description: "Μοσχάρι μαγειρεμένο αργά με κρεμμύδια και κόκκινη σάλτσα.",
    image: "images/stifado.jpg",
    price: 10.5,
    category: "Κυρίως Πιάτο",
  },
  {
    name: "Σουτζουκάκια",
    description: "Επιμήκη κεφτεδάκια σε πικάντικη σάλτσα ντομάτας με κύμινο.",
    image: "images/soutzoukakia.jpg",
    price: 8.0,
    category: "Κυρίως Πιάτο",
  },
  {
    name: "Μπιφτέκια Σχάρας",
    description: "Ψητά μπιφτέκια με κιμά, κρεμμύδι και μυρωδικά.",
    image: "images/biftekia.jpg",
    price: 7.8,
    category: "Κυρίως Πιάτο",
  },
  {
    name: "Χαλβάς",
    description: "Παραδοσιακό γλυκό από σιμιγδάλι, ξηρούς καρπούς και σιρόπι.",
    image: "images/halvas.jpg",
    price: 3.5,
    category: "Γλυκό",
  },
  {
    name: "Μπακλαβάς",
    description: "Φύλλο κρούστας με ξηρούς καρπούς και σιρόπι μελιού.",
    image: "images/baklavas.jpg",
    price: 4.0,
    category: "Γλυκό",
  },
  {
    name: "Γαλακτομπούρεκο",
    description: "Κρέμα σιμιγδαλιού τυλιγμένη σε φύλλο, με σιρόπι.",
    image: "images/galaktoboureko.jpg",
    price: 4.2,
    category: "Γλυκό",
  },
  {
    name: "Λουκουμάδες",
    description: "Τηγανητά ζυμαράκια με μέλι και κανέλα.",
    image: "images/loukoumades.jpg",
    price: 4.5,
    category: "Γλυκό",
  },
  {
    name: "Κανταΐφι",
    description:
      "Σιροπιαστό γλυκό από λεπτές νηματοειδείς ζύμες με ξηρούς καρπούς.",
    image: "images/kantaifi.jpg",
    price: 4.0,
    category: "Γλυκό",
  },
];